apiVersion: batch/v1
kind: Job
metadata:
  name: db-backup-job
spec:
  template:
    spec:
      containers:
      - name: db-backup
        image: postgres:latest
        env:
        - name: PGHOST
          value: "postgres"
        - name: PGDATABASE
          value: "testdb"
        - name: PGUSER
          value: "postgres"
        - name: PGPASSWORD
          value: "password"
        command:
        - "sh"
        - "-c"
        - "pg_dump -h $PGHOST -U $PGUSER $PGDATABASE > /backup/db-backup.sql"
        volumeMounts:
        - name: backup-volume
          mountPath: /backup
      restartPolicy: OnFailure
      volumes:
      - name: backup-volume
        persistentVolumeClaim:
          claimName: backup-pvc
  backoffLimit: 4
